using System;
using System.Collections.Generic;
using System.Text;

namespace SharedUtils.DTOs;

public class HandshakeRequestDto {
    public string SensorId { get; set; } = string.Empty;
    // Diffie-Hellman Public Key (generated by sensor)
    public byte[] PublicKey { get; set; } = Array.Empty<byte>();
}
