using System;
using System.Collections.Generic;
using System.Text;

namespace SharedUtils.DTOs;

public class HandshakeResponseDto {
    public bool IsAccepted { get; set; }
    // Diffie-Hellman Public Key(generated by server)
    public byte[] PublicKey { get; set; } = Array.Empty<byte>();
}