services:
  db:
    image: postgres:15-alpine
    container_name: drus_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: drus_aleksa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # pathOnMyPc:pathInContainer
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # initializes db with needed tables
    restart: always

  primary:
    build:
      context: .
      dockerfile: Server.Dockerfile
    container_name: drus_primary_server
    ports:
      - "8080:8080"
    volumes:
      - ./logs/server:/app/logs  # Server logs
    depends_on:
      - db
    restart: always

  sensor-1:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_1
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=01
      - START_ACTIVE=true
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-1:/app/logs  # Sensor 1 logs
    depends_on:
      - primary
    restart: always

  sensor-2:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_2
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=02
      - START_ACTIVE=true
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-2:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-3:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_3
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=03
      - START_ACTIVE=true
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-3:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-4:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_4
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=04
      - START_ACTIVE=true
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-4:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-5:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_5
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=05
      - START_ACTIVE=false
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-5:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-6:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_6
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=06
      - START_ACTIVE=false
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-6:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-7:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_7
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=07
      - START_ACTIVE=false
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-7:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-8:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_8
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=08
      - START_ACTIVE=false
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-8:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-9:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_9
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=09
      - START_ACTIVE=true
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-9:/app/logs
    depends_on:
      - primary
    restart: always

  sensor-10:
    build:
      context: .
      dockerfile: Sensor.Dockerfile
    container_name: drus_sensor_10
    environment:
      - SERVER_HOST=primary
      - SENSOR_ID=10
      - START_ACTIVE=true
    stdin_open: true
    tty: true
    volumes:
      - ./logs/sensor-10:/app/logs
    depends_on:
      - primary
    restart: always
volumes:
  pgdata: